[program.fs_fat]
path = "fs-fat"
args = [ "site", "drivers/site.bin" ]
target = "site"
file_root = ""

[program.virtio_net]
path = "virtio-net"
args = [ "net" ]
target = "net"
file_root = ""

[program.static_http_server]
path = "static_http_server"
after = [ "site", "net" ]
file_root = "site"
net_root = "net"
