stdin = "uart/0"
stdout = "system/log"
stderr = "system/log"

[program.minish]
path = "minish"
file_root = ""

[program.virtio_net]
path = "virtio_net"
args = [ "net" ]
target = "net"
file_root = ""

[program.static_http_server]
path = "static_http_server"
after = [ "drivers", "net" ]
file_root = "drivers"
net_root = "net"
